name       : screenfetch
version    : 3.9.1
release    : 9
source     :
    - https://github.com/KittyKatt/screenFetch/archive/v3.9.1.tar.gz : aa97dcd2a8576ae18de6c16c19744aae1573a3da7541af4b98a91930a30a3178
license    : GPL-3.0-or-later
component  : system.utils
summary    : Simple system information display from terminal
description: |
    Fetches system/theme information in terminal for Linux desktop screenshots.
setup      : |
    sed 's:pisi:eopkg:g' -i screenfetch-dev
install    : |
    install -Dm00755 screenfetch-dev $installdir/usr/bin/screenfetch
    install -Dm00644 screenfetch.1 $installdir/usr/share/man/man1/screenfetch.1
