name        : screenfetch
version     : 3.6.5
release     : 3
source      :
    - https://github.com/KittyKatt/screenFetch/archive/v3.6.5.tar.gz : b6605a94be9720a5e64778dcc43ddf23e435d6704c5d177b671aa57d34966f20
homepage    : https://github.com/KittyKatt/screenFetch
license     : GPL-2.0+
summary     : Simple system information display from terminal
description : |
    Fetches system/theme information in terminal for Linux desktop screenshots.
setup      : |
build      : |
install    : |
    mkdir -p %installroot%/usr/bin/
    mkdir -p %installroot%/usr/share/man/man1/
    mkdir -p %installroot%/usr/share/doc/screenfetch
    mv screenfetch-dev %installroot%/usr/bin/screenfetch
    mv screenfetch.1 %installroot%/usr/share/man/man1/
    mv * %installroot%/usr/share/doc/screenfetch
