name        : screenfetch
version     : 3.7.0
release     : 5
source     :
    - https://github.com/KittyKatt/screenFetch/archive/v3.7.0.tar.gz : 6711fe924833919d53c1dfbbb43f3777d33e20357a1b1536c4472f6a1b3c6be0
license     : GPL-2.0+
summary     : Simple system information display from terminal
description : |
    Fetches system/theme information in terminal for Linux desktop screenshots.
setup      : |
build      : |
install    : |
    mkdir -p %installroot%/usr/bin/
    mkdir -p %installroot%/usr/share/man/man1/
    mkdir -p %installroot%/usr/share/doc/screenfetch
    mv screenfetch-dev %installroot%/usr/bin/screenfetch
    mv screenfetch.1 %installroot%/usr/share/man/man1/
    mv * %installroot%/usr/share/doc/screenfetch
